### ISSUE TITLE
build error MSB3030

### ISSUE THREAD

**Issue by by321** [Microsoft/caffe#18] opened 2016-02-13 08:50 UTC
Run into four MSB3030 errors during build. This is the first one:

`1>C:\github\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.targets(57,5): error MSB3030: Could not copy the file "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x64\Microsoft.VC120.CRT\msvcr120.dll" because it was not found.`

The corresponding lines in C:\github\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.targets:

` <Target Name="OpenCV_AfterBuild" AfterTargets="AfterBuild">
    <Copy SkipUnchangedFiles="true" SourceFiles="@(CopyToOutput)" UseHardlinksIfPossible="true" DestinationFolder="$(TargetDir)">
      <Output TaskParameter="DestinationFiles" PropertyName="DestinationFiles" />
      <Output TaskParameter="DestinationFiles" ItemName="DestinationFiles" />
      <Output TaskParameter="CopiedFiles" PropertyName="CopiedFiles" />
      <Output TaskParameter="CopiedFiles" ItemName="CopiedFiles" />
    </Copy>
  </Target> `

I don't have VC installed in "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC", but I couldn't find where this path is set in the project files either.

**Comment by jiemojiemo** [comment] 2016-03-04 02:23
I also met the problem,do you have any idea to solve it?

**Comment by Wuranker** [comment] 2016-03-04 03:24
I move "msvcp120.dll" and "msvcr120.dll" from my installation path to "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x64\Microsoft.VC120.CRT\", then move "msvcp120d.dll" and "msvcr120d.dll" to "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\Debug_NonRedist\x64\Microsoft.VC120.DebugCRT\". I solve the problem.

**Comment by AleksandarTomicMS** [comment] 2016-03-04 10:17
This is caused by the HDF5 and LMDB Nuget dependencies. They expect that Visual Studio 2013 is installed at default location ("C:\Program Files (x86)\Microsoft Visual Studio 12.0"), as they target Visual Studio with "$(MSBuildProgramFiles32)\Microsoft Visual Studio 12.0". I think that a clean way to fix this would be to create a [symbolic link ](https://technet.microsoft.com/en-us/library/cc753194.aspx) at this location to your custom visual studio installation path. Other than that you can contact the owners of these Nuget dependencies to fix this, as the problem is in their packages.

**Comment by Codersadis** [comment] 2016-03-14 10:25
Very THX for @Wuranker 's suggestion. 

met this problem too, and
I got my problem fixed with your solution. :-）

**Comment by sasagalic-MSFT** [comment] 2016-03-16 10:19
Closing since several workarounds which seem to fix the issue are proposed. Additionally, 28081992d8a69e3ec83c9fa34e7f8128f00cb11b should have fixed the root cause.

**Closed by sasagalic-MSFT** 2016-03-16 10:19 UTC
